[development]
cors.allowed_origin = "https://digester.local:8080"

[staging]
cors.allowed_origin = "ROCKET_REPLACE_CORS_ALLOWED_ORIGIN"

[development.oauth.github]
provider = "GitHub"
client_id = "ce2e6a7d28bdf8eca16c"
client_secret = "faf62455d8e125a2758cfdbb3c605f249970ba41"
redirect_uri = "https://digester.local:8080"

[staging.oauth.github]
provider = "GitHub"
client_id = "ROCKET_REPLACE_OAUTH_GITHUB_CLIENT_ID"
client_secret = "ROCKET_REPLACE_OAUTH_GITHUB_CLIENT_SECRET"
redirect_uri = "ROCKET_REPLACE_OAUTH_GITHUB_REDIRECT_URI"

[development.databases]
digester = { url = "postgres://postgres@localhost:5432/postgres"}
redis = { url = "redis://127.0.0.1" }

[staging.databases]
digester = { url = "ROCKET_REPLACE_DIGESTER_URL" }
redis = { url = "ROCKET_REPLACE_REDIS_URL" }

[development.tls]
certs = "etc/cert.pem"
key = "etc/key.pem"