image: docker:19.03.1

variables:
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_REGISTRY: "registry.heroku.com"
    CONTAINER_IMAGE: "digester/api"
    HEROKU_APP: "digester-api-integration/web"
    HEROKU_EMAIL: "rethab@pm.me"

services:
  - docker:19.03.1-dind

before_script:
    - docker info
    - cd backend

build:
    stage: build
    script:
        - docker login --username=_ --password=$HEROKU_API_KEY $DOCKER_REGISTRY
        - docker pull $DOCKER_REGISTRY/$HEROKU_APP
        - docker build --tag $CONTAINER_IMAGE:latest --tag $CONTAINER_IMAGE:$CI_BUILD_REF --cache-from $CONTAINER_IMAGE:latest -f api.Dockerfile .
        - docker tag $CONTAINER_IMAGE:latest $DOCKER_REGISTRY/$HEROKU_APP
        - docker push $DOCKER_REGISTRY/$HEROKU_APP

integration:
    stage: deploy
    before_script:
        - apk add curl git gnupg
        - curl https://cli-assets.heroku.com/install.sh | sh
        - heroku --version
        - |
          cat >~/.netrc <<EOF
          machine api.heroku.com
            login $HEROKU_EMAIL
            password $HEROKU_API_KEY
          EOF
        - chmod 600 ~/.netrc
    script:
        - heroku container:release web --app digester-api-integration