image: docker:19.03.1

variables:
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_REGISTRY: "registry.heroku.com"
    API_CONTAINER_IMAGE: "digester/api"
    WORKER_CONTAINER_IMAGE: "digester/worker"
    HEROKU_APP: "digester-api-integration"

services:
  - docker:19.03.1-dind

build:
    stage: build
    before_script:
      - docker info
      - cd backend
    script:
        - docker login --username=_ --password=$HEROKU_API_KEY $DOCKER_REGISTRY

        - docker pull $DOCKER_REGISTRY/$HEROKU_APP/web
        - docker pull $DOCKER_REGISTRY/$HEROKU_APP/worker

        - docker build --tag $API_CONTAINER_IMAGE:latest --tag $API_CONTAINER_IMAGE:$CI_BUILD_REF --cache-from $API_CONTAINER_IMAGE:latest -f api.Dockerfile .
        - docker build --tag $WORKER_CONTAINER_IMAGE:latest --tag $WORKER_CONTAINER_IMAGE:$CI_BUILD_REF --cache-from $WORKER_CONTAINER_IMAGE:latest -f worker.Dockerfile .

        - docker tag $API_CONTAINER_IMAGE:latest $DOCKER_REGISTRY/$HEROKU_APP/web
        - docker tag $WORKER_CONTAINER_IMAGE:latest $DOCKER_REGISTRY/$HEROKU_APP/worker

        - docker push $DOCKER_REGISTRY/$HEROKU_APP/web
        - docker push $DOCKER_REGISTRY/$HEROKU_APP/worker

deploy:
    stage: deploy
    before_script:
        - apk add curl
        - curl https://cli-assets.heroku.com/install.sh | sh
        - heroku --version
        - |
          cat >~/.netrc <<EOF
          machine api.heroku.com
            login $HEROKU_EMAIL
            password $HEROKU_API_KEY
          EOF
        - chmod 600 ~/.netrc
    script:
        - heroku container:release web --app $HEROKU_APP
        - heroku container:release worker --app $HEROKU_APP