image: docker:19.03.1

variables:
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_REGISTRY: "registry.heroku.com"
    API_CONTAINER_IMAGE: "digester/api"
    WORKER_CONTAINER_IMAGE: "digester/worker"
    API_HEROKU_APP: "digester-api-integration"
    WORKER_HEROKU_APP: "digester-worker-integration"

services:
  - docker:19.03.1-dind

build:
    stage: build
    before_script:
      - docker info
      - cd backend
    script:
        - docker login --username=_ --password=$HEROKU_API_KEY $DOCKER_REGISTRY
        - docker pull $DOCKER_REGISTRY/$API_HEROKU_APP/web
        - docker build --tag $API_CONTAINER_IMAGE:latest --tag $API_CONTAINER_IMAGE:$CI_BUILD_REF --cache-from $API_CONTAINER_IMAGE:latest -f api.Dockerfile .
        - docker tag $API_CONTAINER_IMAGE:latest $DOCKER_REGISTRY/$API_HEROKU_APP/web
        - docker push $DOCKER_REGISTRY/$API_HEROKU_APP/web

deploy:
    stage: deploy
    before_script:
        - apk add curl
        - curl https://cli-assets.heroku.com/install.sh | sh
        - heroku --version
        - |
          cat >~/.netrc <<EOF
          machine api.heroku.com
            login $HEROKU_EMAIL
            password $HEROKU_API_KEY
          EOF
        - chmod 600 ~/.netrc
    script:
        - heroku container:release web --app $API_HEROKU_APP