image: docker:19.03.1

variables:
    DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:19.03.1-dind

before_script:
    - docker info
    - cd backend

build:
    stage: build
    only:
        changes:
            - backend/
    script:
        - docker build -t digester/api -f api.Dockerfile .

integration:
    stage: deploy
    script:
        - heroku login --username=_ --password=$HEROKU_AUTH_TOKEN registry.heroku.com
        - docker tag digester/api:latest registry.heroku.com/digester-api-integration/web
        - docker push registry.heroku.com/digester-api-integration/web
        - heroku container:release web --app digester-api-integration