image: docker:19.03.1

variables:
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_REGISTRY: "registry.heroku.com"
    CONTAINER_IMAGE: "digester/api"

services:
  - docker:19.03.1-dind

before_script:
    - docker info
    - cd backend

build:
    stage: build
    script:
        - docker login --username=_ --password=$HEROKU_API_KEY $DOCKER_REGISTRY
        - docker pull $CONTAINER_IMAGE:latest
        - docker build --tag $CONTAINER_IMAGE:latest --tag $CONTAINER_IMAGE:$CI_BUILD_REF --cache-from $CONTAINER_IMAGE:latest -f api.Dockerfile .
        - docker tag $CONTAINER_IMAGE:latest $DOCKER_REGISTRY/digester-api-integration/web
        - docker push $DOCKER_REGISTRY/digester-api-integration/web

integration:
    stage: deploy
    script:
        - heroku container:release web --app digester-api-integration