version: '3'
services:
        redis:
                image: redis
                ports:
                        - "6379:6379"
        postgres:
                build: .
                ports:
                        - "5432:5432"
                environment:
                        - "POSTGRES_HOST_AUTH_METHOD=trust"
