[build]
  base = "frontend"
  publish = "dist"

[context.production]
  command = "npm run build"

[context.develop]
  command = "npm run stage"

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security: max-age=63072000; includeSubDomains; preload