[package]
name = "web-backend"
version = "0.1.0"
authors = ["rethab"]
edition = "2018"

[dependencies]
rocket = "0.4.2"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
url = "2.1.0"

[dependencies.rocket_contrib]
default-features = false
features = ["json", "postgres_pool"]
