[package]
name = "lib-channels"
version = "0.1.0"
authors = ["Reto Habluetzel <rethab@protonmail.ch>"]
edition = "2018"

[dependencies]
chrono = "0.4"
rss = { version = "1.8.0", features = ["from_url"] }
url = "2.1.0"