[package]
name = "lib-digester"
version = "0.1.0"
authors = ["Reto Habluetzel <rethab@protonmail.ch>"]
edition = "2018"


[dependencies]
lib-db = { path = "../lib-db" }
lib-messaging = { path = "../lib-messaging" }
chrono = "0.4"
chrono-tz = "0.5"
either = "1"